os:
        - osx

language:
        - cpp

compiler:
        - gcc

before_install:
        - brew update
        - brew list | grep perl || brew install perl
        - brew outdated perl || brew upgrade perl
        - brew list | grep glib || brew install glib
        - brew outdated glib || brew upgrade glib
install:
        # devkitARM Installation
        - cd ~/
        - mkdir ${DEVKITPRO}
        - cd ${DEVKITPRO}
        - wget 'https://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitARMupdate.pl'
        - perl -- devkitARMupdate.pl

script:
        # Fix stuffs
        - cd ~/build/jellyfishcoder/tremorsnDS
        - make
